### ISSUE TITLE
Change default settings

### ISSUE THREAD

**Issue by thunder4** [qzb/dustman#11]
Hi
I am working on a script based on your add-on and Selenium(http://www.seleniumhq.org)
Unfortunately Selenium does not load add-ons' custom settings but only the default ones.
Can you please edit the settings like this

Close inactve tabs after (minutes): 1
Minimum number of tabs: 1
Number of closed tabs showed in panel: 1

and send me the edited version?
Thank you in advance

**Comment by qzb** [comment]
No problem, I've packed it with zip, because github doesn't accept xpi files in comments.
[dustman.zip](https://github.com/qzb/dustman/files/286826/dustman.zip)

It isn't signed, so you must disable [some security settings](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_override-add-on-signing-advanced-users).
