### ISSUE TITLE
Dustman loses all saved tabs when Firefox shutdown

### ISSUE THREAD

**Issue by agawish** [qzb/dustman#27]
Firefox 57, windows update forces Firefox to shutdown, reopened, Dustman doesn't have any of my saved closed tabs!

**Comment by mbid** [comment]
Yeah, I can see why this is bad. However, I don't want to write the closed tabs to the disk: Imagine you have configured firefox so that the history is cleared on exit. Wouldn't you be surprised if Dustman kept the (part of) the history anyway? As far as I know, there is no way to query firefox's settings from within a WebExtension, so I decided to be conservative and not write the history to the disk at all.

There could maybe be an option to make Dustman do, regardless of firefox's settings. I'll think about it.

**Comment by agawish** [comment]
I believe as you mentioned a configuration to save it in a specific bookmarked folder would be nice. 
If you want I can help with the development of this, as this is crucially important to me.

**Comment by mbid** [comment]
@agawish I've just pushed a version that should save history to disk if you opt-in in the settings. Let me know whether it works for you.

**Comment by agawish** [comment]
Works like a charm, thanks.
