### ISSUE TITLE
Firefox ESR 52.5

### ISSUE THREAD

**Issue by chdid** [qzb/dustman#28]
Hello
I can't use Dustman with the last Firefox ESR (52.5).
The tabs do not close.
Could you tell me if there is a special configuration.
Chdid

**Comment by mbid** [comment]
Hi Chdid,
sorry to hear that. I think this is because Firefox 52 doesn't properly support the way addons have to be developed so that they work in Firefox 57. Maybe you can use an older version of dustman. Try version 1.2.1, which can be downloaded from [Dustman's version history on addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/dustman/versions/).

**Comment by chdid** [comment]
Thank you.
1.2.1 is OK with Firefox ESR.
