### ISSUE TITLE
Feature request: allow active tab to be closed

### ISSUE THREAD

**Issue by Cegir** [qzb/dustman#30]
Here's the thing, I'm searching for desperately for a mod that allow me to close actual tab, or firefox, after a set amount of time, but I don't.

Like I watch my screen from the bed before sleeping, I search for something that close browser, like screensaver/shutdown does not occur while the PC is in use (eg a video running, like Twitch or Youtube).

**Comment by mbid** [comment]
Hi Cegir,
this is not the main use case for this addon. I'm sure there are already programs for your OS that let you suspend after X minutes. If you're on one of the more popular GNU/Linux distributions, chances are `sleep 3600; systemctl suspend` will wait for an hour and then suspend.

That said, here's what I could do for you: Currently, dustman will always leave at least one tab open because "Minimum number of tabs per window" can't be set to 0 or lower. I can allow setting this to 0. This would mean that your browser windows close automatically if unused for more than "Minimum backround time". Would that solve your problem?
